#!/bin/sh
key_name=$1
key_size=${2-1024}
openssl genrsa -out $key_name $key_size
openssl pkcs8 -topk8 -in $key_name -out $key_name.pub -nocrypt
openssl rsa -in $key_name -outform PEM -pubout -out $key_name.pub
chmod 600 $key_name